### ISSUE TITLE
After Update To 1.10.3, show errors "t.week is not a function"

### ISSUE THREAD

**Issue by illusi03** [iamkun/dayjs#1328]
**Describe the bug**
Show error, t.week is not a function. After upgrade to 1.10.3

**Expected behavior**
I expected this package No bugs :)

**Information**
 - Day.js Version [v.1.10.3]
 - OS: [windows 10, 64bit]
 - Browser [chrome]
 - Time zone: [GMT 08:00 DST (Pacific Daylight Time)]

**Comment by illusi03** [comment]
<img width="1210" alt="Screen Shot 2021-01-11 at 11 31 19" src="https://user-images.githubusercontent.com/52351532/104148614-89e52e80-5405-11eb-8bba-8e5389ae98e4.png">

There the error.

I downgrade dayjs to 1.8.30, and remove dayjs installed, **has solved** 

Thanks in advice ...

**Comment by iamkun** [comment]
A reproduction demo or code, please?

**Comment by mikerourke** [comment]
FYI, @illusi03, I ran into this issue as well. The workaround is to import/use the `isoWeek` plugin:
```ts
import isoWeek from "dayjs/plugin/isoWeek";

//...

dayjs.extend(isoWeek);
```

I think adding a check for whether the `.isoWeek()` method is available on `this` should fix it (https://github.com/iamkun/dayjs/blob/dev/src/plugin/advancedFormat/index.js#L33). I can try putting a PR in with a fix tomorrow unless someone else beats me to it.

**Comment by iamkun** [comment]
Can you please confirm how did you use this plugin? Have you format in `'WW'` or `W` like

**Comment by mikerourke** [comment]
I needed to change the format of a date to adhere to the HTML week input, which is `yyyy-Www`, where the uppercase `W` is the actual letter "W", so I had to escape it with `[W]`.

I don't actually use the `isoWeek` plugin, I use the `weekOfYear` plugin to get/set week numbers. I just added `isoWeek` to get around the error. I'm not sure if that answers your question 🤷‍♀️

**Comment by iamkun** [comment]
Well, that's the main reason. You should escape is with `[W]` to get `W` string, or use isoWeek plugin to `format('W')` according to doc

**Comment by tukusejssirs** [comment]
I have the same problem, however, I need `ww` to be the ISO week number. Tested on `dayjs@1.11.1`.

MWE:

```js
const dayjs = require('dayjs')

const advancedFormat = require('dayjs/plugin/advancedFormat')
const utc = require('dayjs/plugin/utc')
const timezone = require('dayjs/plugin/timezone')
const isoWeek = require('dayjs/plugin/isoWeek')

dayjs.extend(advancedFormat)
dayjs.extend(utc)
dayjs.extend(timezone)
dayjs.extend(isoWeek)

dayjs.tz.setDefault('Europe/Bratislava')

const now = dayjs()

// console.log(`w :`, now.format('w'))  // Does not work
console.log(`ww :`, now.format('ww'))  // Does not work
```

**Comment by GagnDeep** [comment]
@tukusejssirs [weekOfYear](https://day.js.org/docs/en/plugin/week-of-year) plugin solves this issue. Try extending this plugin before using any week based formatting

```javascript
import weekOfYear from "dayjs/plugin/weekOfYear";
dayjs.extend(weekOfYear)
```

**Comment by tukusejssirs** [comment]
Thanks, @GagnDeep, for helping me out! :wink: It indeed works as expected.

However, the [docs](https://day.js.org/docs/en/get-set/iso-week) are not stating the dependency on `WeekOfYear`. They actually state that it depends on `IsoWeek`.

I think the docs should provides use plugin dependency graph which would inform users of each and every plugin required by a particular plugin. And also state the order of extending `dayjs` if that is important.

Of course, this is a bit OT topic to this issue.

**Comment by GagnDeep** [comment]
@tukusejssirs To get iso week number you need to use `WW` instead of `ww`. It's in the table of accepted formats for [advancedFormat](https://day.js.org/docs/en/plugin/advanced-format) plugin.

```javascript
const dayjs = require('dayjs')

const advancedFormat = require('dayjs/plugin/advancedFormat')
const isoWeek = require('dayjs/plugin/isoWeek')
const weekOfYear = require('dayjs/plugin/weekOfYear')

dayjs.extend(advancedFormat)
dayjs.extend(weekOfYear)
dayjs.extend(isoWeek)


console.log(`dayjs :`, now.format('ww'))   // Output: 19
console.log(`iso   :`, now.format("WW"))  // Output: 18
```

**Comment by tukusejssirs** [comment]
> @tukusejssirs To get iso week number you need to use `WW` instead of `ww`. It's in the table of accepted formats for [advancedFormat](https://day.js.org/docs/en/plugin/advanced-format) plugin.

🤦‍♂️ Argh, you’re right I’ve read the table, but somehow missed the casing of `W`.

I’m sorry for the noise snd thank you for your patience and help! :pray:

**Comment by dawangong** [comment]
> @tukusejssirs [weekOfYear](https://day.js.org/docs/en/plugin/week-of-year) plugin solves this issue. Try importing this plugin before using any week based formatting from `advancedFormat` plugin
> 
> ```js
> import weekOfYear from "dayjs/plugin/weekOfYear";
> import advancedFormat from "dayjs/plugin/advancedFormat"
> 
> dayjs.extend(weekOfYear)
> dayjs.extend(advancedFormat)
> 
> const now = dayjs()
> console.log(`ww :`, now.format('ww')) 
> ```

Thanks, @GagnDeep, for helping me out!  It worked as expected.
