### ISSUE TITLE
TypeError: dayjs_1.default is not a function

### ISSUE THREAD

**Issue by dockleryxk** [iamkun/dayjs#475]
When updating the dayjs package from 1.8.0 to 1.8.3, I'm getting this error.

I changed my import from `import * as dayjs from 'dayjs';` to `import dayjs from 'dayjs';` which let me compile, but this error what this result.

Here is the line of code for the error:

```const today = dayjs().format('YYYY-MM-DD');```

**Comment by adamfoerster** [comment]
same error here

**Comment by iamkun** [comment]
Bug confirmed. We changed index.d.ts from `export = dayjs;` to `export default dayjs`.

TS expert help wanted.

**Comment by iamkun** [comment]
Seems add `"esModuleInterop": true,` to tsconfig would solve this issue, but should a better way.

**Comment by iamkun** [comment]
Just released v1.8.4 to revert this change. Please remain using
```
import * as dayjs from 'dayjs'
```
in a TypeScript project.

And discussion still welcome

**Comment by tsiq-jeremy** [comment]
I also saw this issue when `tsconfig` had this set `"allowSyntheticDefaultImports": true,`.

**Comment by iamkun** [comment]
@tsiq-jeremy Your Day.js version and TS version, please.

**Comment by tsiq-jeremy** [comment]
Ahh actually it was a bit more complicated I'm realizing then what I wrote. Basically when you have a library compiling with tsconfig `allowSyntheticDefaultImports` and then a consuming application that does not use that setting, we got that error. Both the library and consuming application had dayjs as `dependencies`. Using TS 3.0.3 and dayjs 1.8.9.

I think I may write this all up in a separate issue, but I think a root cause to this is when using tsconfig `allowSyntheticDefaultImports` you have to then change how you import dayjs from `import * as dayjs from 'dayjs';` to `import dayjs from 'dayjs';` . 

Looks like adding `export as namespace dayjs;` to the .d.ts file could would allow you to import dayjs both ways. Seems like what React and other libraries do. This allows for importing dayjs the same way regardless of if you have that tsconfig variable set.

**Comment by danawoodman** [comment]
This is an issue for me in a Next.js project. On the server side when rendering a React component I get:

```
TypeError: dayjs__WEBPACK_IMPORTED_MODULE_0___default(...)(...).fromNow is not a function
```

Works on the client rendering cycle of Next.js but not the Node side.

Using `1.8.29`

**Comment by iamkun** [comment]
@danawoodman a reproduction demo repo, please?

**Comment by danawoodman** [comment]
@iamkun I figured it out, it was because I imported the "relativeTime" extension in my entry point but didn't import it where I was using it. I just assumed that it would work at the entry point but moving it right next to the code in question fixed it:

```tsx
import dayjs from "dayjs"
import relativeTime from "dayjs/plugin/relativeTime"

dayjs.extend(relativeTime)

console.log(dayjs(new Date("jan 1, 2020").fromNow())
```

**Comment by ivictbor** [comment]
Had the same issue after update to webpack5, probably will help someone also: https://hinty.io/devforth/fix-webpack-imported-module-is-not-a-function-for-webpack5/

**Comment by AndresAusecha** [comment]
This exception is still thrown, when you use dayjs in tests triggered by Jest you get it sometimes and for some components even tho the app in real-time works perfectly.

Weird issue

**Comment by ylahssini** [comment]
Same issue for me, the weird thing is that in the first time is working, i don't know why is show me this error.

**Comment by thomasFjorstad** [comment]
`TypeError: dayjs is not a function` when running test from react-test-library.

**Comment by vagoel** [comment]
My jest tests are failing because its is unable to recognize `dayjs`

![image](https://user-images.githubusercontent.com/8045008/133422505-ecc968c1-370c-4b36-a827-a5fa9b2478c9.png)

In the file , i have used dayjs like this - 
```import * as dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';

dayjs.extend(relativeTime);```

Only the tests are failing , functionality is working fine.

**Comment by JesusTheHun** [comment]
This repo feels forsaken.

**Comment by JesusTheHun** [comment]
> I'm still getting the same error in end of 2021. Any new ideas?

Yes, I moved to [Luxon](https://github.com/moment/luxon), bigger package size but at least it doesn't f*** up my tests.

**Comment by hixus** [comment]
At least for me the issue was importing dayjs directly `import dayjs from "dayjs";` in test file. Instead I should have used my lib file that adds the plugins `import dayjs from "src/lib/dayjs";`

Don't know why the types in app itself worked fine but jest behaviour also seems correct.

**Comment by nicohagen** [comment]
> At least for me the issue was importing dayjs directly `import dayjs from "dayjs";` in test file. Instead I should have used my lib file that adds the plugins `import dayjs from "src/lib/dayjs";`
> 
> ```
> # src/lib/dayjs.ts
> import dayjs from "dayjs";
> import relativeTime from "dayjs/plugin/relativeTime";
> 
> dayjs.extend(relativeTime);
> 
> export default dayjs;
> ```
> 
> Don't know why the types in the app worked but jest behaviour also seems correct.

Making dayjs and its plugin default imports actually solved the Jest test failing issue for me. Thanks!

**Comment by nicohagen** [comment]
Using default imports
```
import dayjs from 'dayjs'
import relativeTime from 'dayjs/plugin/relativeTime'
```
 in the tested module instead `import * as ...` did the trick for me.

**Comment by sohammondal** [comment]
I was facing this issue as well. I added `allowSyntheticDefaultImports: true` in tsconfig.json & `import dayjs from 'dayjs'` worked for me.

**Comment by yohanelly95** [comment]
I am trying this in a React project (JS not TS) and it does not work. I get the error `TypeError: dayjs__WEBPACK_IMPORTED_MODULE_5___default.a.unix(...).utc is not a function`

My code is: 
`import dayjs from "dayjs";`
`export const unixToDate = (unix, format = "YYYY-MM-DD") => {
  return dayjs.unix(unix).utc().format(format);
};`

**Comment by VRedondo** [comment]
Facing similar issue

My code is

```js
import dayjs from 'dayjs';

const createdAt = dayjs.utc(review.createdDt || '')
```

```bash
TypeError: dayjs__WEBPACK_IMPORTED_MODULE_1__.utc is not a function
```

tsconfig is already had `allowSyntheticDefaultImports: true` 

dayjs version 1.10.4

**Comment by Vanessa-Ap-Ferreira** [comment]
> 

I need to buy you a beer

**Comment by Vanessa-Ap-Ferreira** [comment]
> Seems add `"esModuleInterop": true,` to tsconfig would solve this issue, but should a better way.

I need to buy you a beer

**Comment by yimmymoore** [comment]
I have tried all the suggestions in this thread. Warning to anyone trying to publish a typescript npm package artifact in azure with this. It works like a charm in the artifact repo, but once distributed to your development-repo it just wont work anymore. Just use a different library.

**Comment by JamesScript** [comment]
For anyone else coming to this with a similar issue to me, my problem was that the `dayjs.extend(minMax)` code was being called in the parent of the component I was testing. So when running the app the `dayjs.max` method existed, but the test suite only imported the component and not its parent, therefore the plugin wasn't being applied to dayjs.

**Comment by keeganteetaert** [comment]
This works for me when I export the plugins along with the default.

```js
// dayjs.ts
import dayjs from 'dayjs';
import utc from 'dayjs/plugin/utc';
import isTomorrow from 'dayjs/plugin/isToday';
import isToday from 'dayjs/plugin/isTomorrow';
import relativeTime from 'dayjs/plugin/relativeTime';

dayjs.extend(utc);
dayjs.extend(isToday);
dayjs.extend(isTomorrow);
dayjs.extend(relativeTime);

export {
  dayjs, 
  utc, isToday, isTomorrow, relativeTime, // important to not get compiling errors when using these plugins
};

```

This then works in another file
```js
// anotherFile.js
import { dayjs } from './dayjs';
dayjs.utc();
```

**Comment by merajseraji** [comment]
@iamkun any news about update and fix this bug dude?
is it fix in Dayjs 2.0 alpha?

Don't make us look for another package!😥

**Comment by CasuallyCaffeinated** [comment]
Any update on fixing this? I'm working in a JS React Native project. This is really quite frustrating. 

```
 FAIL  src/utils/__tests__/isDateSameOrAfter.test.js
  isDateSameOrAfter()
    when the date string passed as a param, is BEFORE today's date
      ✕ isDateSameOrAfter() return false (1 ms)

    TypeError: t is not a function

       9 |
      10 | export const isDateSameOrAfter = (date) => {
    > 11 |     dayjs.extend(isSameOrAfter);
         |           ^
      12 |     return dayjs().isSameOrAfter(date);
      13 | };
      14 |

      at Function.extend (node_modules/dayjs/dayjs.min.js:1:6551)
      at isDateSameOrAfter (src/utils/day-js/isDateSameOrAfter.js:11:11)
      at Object.<anonymous> (src/utils/__tests__/isDateSameOrAfter.test.js:10:45)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.139 s
```

**Comment by Mng12345** [comment]
Same error with version v1.11.6!

**Comment by BrunoQuaresma** [comment]
The error that I see on VSCode when using `import * as dayjs from "dayjs"` is:
```
Type 'typeof import("/project/node_modules/dayjs/index.d.ts")' has no call signatures.
```

```
import * as dayjs from "dayjs"

export function createDayString(time: string): string {
  return dayjs().to(dayjs(time))
}
```
<img width="1139" alt="Screen Shot 2022-11-14 at 21 09 14" src="https://user-images.githubusercontent.com/3165839/201794156-391a4d10-ff15-47dc-b680-cb60c2177cbf.png">

**Comment by rombat** [comment]
Same issue here, in a React project:
`TypeError: dayjs__WEBPACK_IMPORTED_MODULE_30___default.a.endOf is not a function`

**Comment by gsben** [comment]
> Seems add `"esModuleInterop": true,` to tsconfig would solve this issue, but should a better way.
nice

**Comment by tgoulder4** [comment]
> Just released v1.8.4 to revert this change. Please remain using
> 
> ```
> import * as dayjs from 'dayjs'
> ```
> 
> in a TypeScript project.
> 
> And discussion still welcome

I now get `This expression is not callable.` when using `dayjs()`

**Comment by vallemar** [comment]
same error here, nothing works

**Comment by master117** [comment]
Still facing this issue. Impossible to use jest + ts while using extend.

```
// Setup DayJS Plugins
import dayjs from "dayjs";
import weekOfYear from "dayjs/plugin/weekOfYear";
import quarterOfYear from "dayjs/plugin/quarterOfYear";
import isoWeek from "dayjs/plugin/isoWeek";

dayjs.extend(weekOfYear);
dayjs.extend(quarterOfYear);
dayjs.extend(isoWeek);
```

```
Test suite failed to run

    TypeError: dayjs_1.default.extend is not a function

       5 | import isoWeek from "dayjs/plugin/isoWeek";
       6 |
    >  7 | dayjs.extend(weekOfYear);
         |       ^
       8 | dayjs.extend(quarterOfYear);
       9 | dayjs.extend(isoWeek);
      10 |
```

when I use

`import * as dayjs from "dayjs";`

I get a TS error. https://github.com/iamkun/dayjs/issues/1132#issuecomment-1840251458

If I then also add, in tsconfig.json:

```
  "compilerOptions": {
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
```

I get:

```
Test suite failed to run

    src/a.tsx:61:55 - error TS2349: This expression is not callable.
      Type 'typeof import("bla/node_modules/dayjs/index.d.ts")' has no call signatures.

    61                 As Of: dayjs(a).format("YYYY-MM-DD")
                                                             ~~~~~

      src/dayjs.ts:2:1
        2 import * as dayjs from "dayjs";
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.
```

The only way around was to move all my dayJS calls to wrapper functions in a separate file and mock each and every single one. This is unsustainable.

**Comment by r-b0rges** [comment]
is there a way to skip type errors?

**Comment by swimhiking** [comment]
wondering how to do unit tests with dayjs, I got dayjs_1.default or dayjs_1.default.extend is not a function error no matter how I try:

jest.mock('dayjs', () => {
  const originalModule = jest.requireActual('dayjs');
  return {
    __esModule: true,
    ...originalModule,
    default: {
      dayjs: jest.fn().mockResolvedValue({ default: { extends: jest.fn() } }),
      extends: jest.fn(),
    },
  };
});

**Comment by rikez** [comment]
@swimhiking 

I'm using`dayjs@1.11.11`.

My tests were failing because I have a dependency on [rc-picker](https://www.npmjs.com/package/rc-picker) which also depends on dayjs. To fix, I installed dayJs as a devDependency, and mapped the module to the correct entrypoint file.

```
  moduleNameMapper: {
    "^dayjs$": "<rootDir>/node_modules/dayjs/dayjs.min.js"
  },
```

**Comment by gmzacharydovel** [comment]
> What were the benefits of that change? Couple of reasons why to avoid default exports: https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html

In my experience, this is the path of good intentions that makes a site's initial load be MB instead if KB.  Not exactly 1-to-1, but usually together.
