### ISSUE TITLE
Humanize require both duration and relativeTime plugins

### ISSUE THREAD

**Issue by doliG** [iamkun/dayjs#890]
**Describe the bug**

Hello guys, and thank you for this awesome lib.

I am trying to migrate from moment to dayjs, and I found something which IMHO is weird:  it looks like humanize does not work without _duration_ **and**  _relativeTime_ plugin.

This script, which is a copy/paste from the humanize doc, result to an error:

```js
const dayjs = require("dayjs")
const duration = require("dayjs/plugin/duration")

dayjs.extend(duration)

const result = dayjs.duration(1, "minutes").humanize() // a minute
console.log({ result })
```

```
TypeError: t(...).add(...).locale(...).fromNow is not a function
    at s.u.humanize (/private/tmp/dayjstest/node_modules/dayjs/plugin/duration.js:1:2489)
```

Error logs: https://pastebin.com/rGhgezBU

But, adding relativeTime plugin make it works:

```js
const dayjs = require("dayjs")
const duration = require("dayjs/plugin/duration")
const relativeTime = require('dayjs/plugin/relativeTime')

dayjs.extend(duration)
dayjs.extend(relativeTime)

const result = dayjs.duration(1, "minutes").humanize() // a minute
console.log({ result })
// { result: 'a minute' }
```

**Expected behavior**

Well, I feel like plugin should work in isolation. If it is not possible, maybe it can be a good thing to update the documentation and wrote that [humanize](https://day.js.org/docs/en/durations/humanize#__docusaurus) require both _relativeTime_ and _duration_ plugins.

But, I'm still a beginner with dayjs, so maybe I just missed something big. What do you think ? 

**Information**
 - Day.js Version :v1.8.25
 - OS: MacOS Mojave
 - Node: 13.11.0

**Comment by iamkun** [comment]
My bad, Humanize dependent on RelativeTime plugin to work

Doc updated https://day.js.org/docs/en/durations/humanize

**Comment by doliG** [comment]
Thanks you for your quick response :)
