### ISSUE TITLE
`dayjs` does not actually support Node.js ESM

### ISSUE THREAD

**Issue by CyanSalt** [iamkun/dayjs#1765]
Node.js has implemented native support for ESM in the real world, and the community is increasingly recommending the use of ESM instead of CommonJS (e.g: https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77). 

I noticed that `dayjs` actually publishes the `esm` directory, which contains the compiled product of the ESM syntax, see #1298. Although the `"module"` field of `package.json` was removed in #1314, the contents of `esm` are actually still available in the `<script type="module">` in browsers or in bundling tools such as `webpack`.

Unfortunately, Node.js [requires more than that](https://nodejs.org/api/esm.html#enabling) for ESM. Since this is a CommonJS package, the ESM files it provides must use the `.mjs` extension to be properly parsed by Node.js.

I can get a few ways to solve this problem, but perhaps none of them are very good:
- The easiest way to make it work is to replace the `.js` extension with `.mjs` in `build/esm.js`, but obviously this will cause breaking changes for scenarios that already use ESM files.
- We can also publish a new `node-esm` directory for `.mjs` files for Node.js. But `node-esm` is not a good name for forward compatibility reasons.
- Further, as described in #1314, continue to push the implementation of the `dayjs-esm` package, just like `lodash-es`.

I'm not sure if you have plans for this in terms of Node.js ESM, but I think that this is the way to go.

**Comment by katerlouis** [comment]
Any news here?

**Comment by benmccann** [comment]
2.0 supports ESM

**Comment by steffanhalv** [comment]
> 2.0 supports ESM

```js
import dayjs from 'https://cdn.jsdelivr.net/npm/dayjs@2.0.0-alpha.2/dist/index.mjs'
console.log(dayjs())
```

**Comment by michaelhays** [comment]
Looks like the 2.0 alpha may be abandoned -- no new commits or releases in 6 months.

Is there a plan to re-open work on 2.0, or to bring ESM support to 1.0?

**Comment by neilsoult** [comment]
> Looks like the 2.0 alpha may be abandoned -- no new commits or releases in 6 months.
> 
> Is there a plan to re-open work on 2.0, or to bring ESM support to 1.0?

BUMP

**Comment by MonsterDeveloper** [comment]
Any ETA on ESM arrival on NPM?

**Comment by DaniilIsupov** [comment]
I'm also waiting for Node.js ESM support

**Comment by Lauro235** [comment]
Would be great to get ESM support!

**Comment by andyg3** [comment]
Another vote here for ESM support.

**Comment by n3ih7** [comment]
Come on! Where is EAM support?

**Comment by 0x80** [comment]
Damn I just wasted hours on this 🤦‍♂️ When converting a large codebase to a monorepo, I kept getting errors like this:

> Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/me/myproject/
> services/fns/node_modules/dayjs/plugin/advancedFormat' imported from /Users/me/myproject/services/fns/dist/index.js
> Did you mean to import dayjs@1.11.10/node_modules/dayjs/plugin/advancedFormat.js?

I couldn't figure it out because my bundled shared packages output looked correct, but I assumed it must be a mistake in some configuration. I tried everything I could think of before landing here.

I did not imagine a popular library like this would not have support for ESM yet in 2024. 

I'll give 2.0 a try, but it sounds like it's time to move to an alternative, possibly the new [Temporal API](https://tc39.es/proposal-temporal/docs/)...?

**Comment by 0x80** [comment]
The types in 2.0 alpha didn't seem to work for me. For example, TS didn't recognize that `.utc()` was available after applying the extension. I ended up sticking `.js` to the v1 imports and that works for now.

**Comment by blackfalcon** [comment]
Running SSR build with Svelte/Vite 

```
(node:29857) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/dalesande/src/personal/sveltekit-auro/node_modules/dayjs/esm/index.js:1
import * as C from './constant';
```

Not sure if this is the fix you want, but I simply updated all the JS references to be `.mjs` and that fixed it. I pushed up a branch of the changes. The tests don't work, but thought this would be easy to see the diff. 

https://github.com/iamkun/dayjs/compare/dev...blackfalcon:dayjs:dev

**Comment by alex-arriaga** [comment]
Another vote here for ESM support.

**Comment by codyfrisch** [comment]
Two years on and nothing on proper ESM support tells me this is a dead end project and I need to migrate my code to another library. ESM is the only way forward, that is written on the wall.

**Comment by michaelhays** [comment]
> Two years on and nothing on proper ESM support tells me this is a dead end project and I need to migrate my code to another library. ESM is the only way forward, that is written on the wall.

Pretty much, I'm just waiting patiently for https://github.com/tc39/proposal-temporal to hit Stage 4 so I can migrate my Day.js code to that :pray:

**Comment by codyfrisch** [comment]
> > Two years on and nothing on proper ESM support tells me this is a dead end project and I need to migrate my code to another library. ESM is the only way forward, that is written on the wall.
> 
> Pretty much, I'm just waiting patiently for https://github.com/tc39/proposal-temporal to hit Stage 4 so I can migrate my Day.js code to that 🙏

That would be ideal, but I have a requirement for format strings, and unfortunately I'm dealing with interop where there is an expectation for the moment.js/day.js style formatting strings. I suppose I could write something that converts between them... and use date-fns (I am assuming temporal is going to use unicode tokens like date-fns since its a standard).

**Comment by blackfalcon** [comment]
> Two years on and nothing on proper ESM support tells me this is a dead end project and I need to migrate my code to another library. ESM is the only way forward, that is written on the wall.

The current version covers my use case, time to fork.

**Comment by manchicken** [comment]
With all of the folks forcing us to ESM, regardless of technical benefit, this seems like it's going to continue to be a problem.

**Comment by manchicken** [comment]
> You mean developers choosing to use an official ECMAScript standard that is intended to be universal between backend and frontend, supports async module loading, and tree-shaking is "forcing" you to not live in the past? Got it.

You're coming in hot, friend. I'm talking about the trend of module maintainers changing away from supporting commonjs and suggesting that it's "where the ecosystem is going" while only polling TypeScript enthusiasts and React developers. 

There are a number of folks using Node for automation and systems-level scripts, and it seems all of the front-end web enthusiasm is the only thing anybody really cares to consider when making these decisions.

**Comment by codyfrisch** [comment]
> > You mean developers choosing to use an official ECMAScript standard that is intended to be universal between backend and frontend, supports async module loading, and tree-shaking is "forcing" you to not live in the past? Got it.
> 
> You're coming in hot, friend. I'm talking about the trend of module maintainers changing away from supporting commonjs to ESM-only, and suggesting that it's "where the ecosystem is going" while only considering the preferences TypeScript enthusiasts and React developers.
> 
> There are a number of folks using Node for automation and systems-level scripts, and it seems all of the front-end web enthusiasm is the only thing anybody really cares to consider when making these decisions.

Okay boomer. J/K. I've never advocated removing CJS entirely. But refusing to support ESM **properly** is a great way to see your library die. Only reason I keep dayjs around is because it adheres to the non-standard formatting strings moment used. (there is a unicode standard that date-fns follows, and I expect temporal will follow.)

And reality check 97% of my projects are node for automations and system level scripting. All has been ESM for well over a year. I've worked around DayJS by implementing a helper that just replaces Y with y and D with d in formatting strings and use date-fns. (Format input is user supplied and I need to support their legacy expectation.)

So maybe its a hot take, but nothing is holding you back except yourself.

**Comment by manchicken** [comment]
> Okay boomer. J/K. I've never advocated removing CJS entirely. But refusing to support ESM **properly** is a great way to see your library die. Only reason I keep dayjs around is because it adheres to the non-standard formatting strings moment used. (there is a unicode standard that date-fns follows, and I expect temporal will follow.)
> 
> And reality check 97% of my projects are node for automations and system level scripting. All has been ESM for well over a year. I've worked around DayJS by implementing a helper that just replaces Y with y and D with d in formatting strings and use date-fns. (Format input is user supplied and I need to support their legacy expectation.)
> 
> So maybe it's a hot take, but nothing is holding you back except yourself.

I'm sorry friend, but you being fine with something is not an adequate substitute for the broader community being considered in decision-making. 

Folks making decisions to break away from one approach or another _do_ have an impact on a great number of people, and as a maintainer of several projects myself I'm always careful to be cognizant of that fact. I am genuinely glad to hear that this time it wasn't you. As you continue your own work, I sincerely hope that you continue your streak of good luck.

How we treat each other _does_ matter.

**Comment by codyfrisch** [comment]
Yes, how we treat each other does matter. Preferably, by not letting our own selfish need to be lazy and not solve problems hold the community back.

**Comment by codyfrisch** [comment]
Also what kind of cuck puts pronouns in their profile in 2024?

**Comment by manchicken** [comment]
> looks bad but work fine  🙅🏻‍♀️
> 
> <img width="432" alt="image" src="https://github.com/iamkun/dayjs/assets/17941407/e2253ec2-12ed-42a9-80f7-2ed481342005">
> 
> 
> 
> Has there been any progress on this issue?

I confirm that this works.

**Comment by robertIsaac** [comment]
> > From [@codyfrisch](https://github.com/codyfrisch):
> > You mean developers choosing to use an official ECMAScript standard that is intended to be universal between backend and frontend, supports async module loading, and tree-shaking is "forcing" you to not live in the past? Got it.
> 
> You're coming in hot, friend. I'm talking about the trend of module maintainers changing away from supporting commonjs to ESM-only, and suggesting that it's "where the ecosystem is going" while only considering the preferences TypeScript enthusiasts and React developers.
> 
> There are a number of folks using Node for automation and systems-level scripts, and it seems all of the front-end web enthusiasm is the only thing anybody really cares to consider when making these decisions.

but you can import/require esm everywhere without a problem
but you can't say the same about cjs!!

**Comment by drdreo** [comment]
Converting it to ESM is quicker than having this discussion https://www.npmjs.com/package/esm-dayjs . Converted to ESM with  vitest, rolldown oxlint and oxfmt.

**Comment by disarticulate** [comment]
It's essentially already ESM, but the package.json and build artifacts need to be changed for direct compatibility. I tried to vibe code something, but it's still a mess. The eco system move to es6 is confusing af.

I believe this works in library mode for vite:
```
import dayjs from 'dayjs/esm'
import utc from 'dayjs/esm/plugin/utc'
import isBetween from 'dayjs/esm/plugin/isBetween'
import duration from 'dayjs/esm/plugin/duration'
import timezone from 'dayjs/esm/plugin/timezone'
import relativeTime from 'dayjs/esm/plugin/relativeTime'
import objectSupport from 'dayjs/esm/plugin/objectSupport'
import quarterOfYear from 'dayjs/esm/plugin/quarterOfYear'
import advancedFormat from 'dayjs/esm/plugin/advancedFormat'
import customParseFormat from 'dayjs/esm/plugin/customParseFormat'
```

But I had to exclude it from building:
```
    commonjsOptions: {
      exclude: ['**/dayjs/*'],
      requireNodeBuiltins: true,
    },
```

Otherwise, the build/dev system seems to think the entrypoint is 'dayjs.min.js' even though there's a whole esm folder that's available.

**Comment by mylifeandcode** [comment]
One more vote for proper ESM support.

**Comment by paranoidPhantom** [comment]
And another vote for ESM

**Comment by silverwind** [comment]
Proper ESM is needed, I've been running into https://github.com/sxzz/rolldown-plugin-dts/issues/230 because of `dayjs`'s weird legacy `export = ` type exports.

**Comment by Vinccool96** [comment]
@iamkun Any plan for this?
