### ISSUE TITLE
Type issues

### ISSUE THREAD

**Issue by Mister-Hope** [iamkun/dayjs#1311]
**Describe the bug**

I am metting `Error in render: "TypeError: dayjs__WEBPACK_IMPORTED_MODULE_0__ is not a function"` when using webpack with the latest version. 

**Addtional Info**: Everything works fine in 1.9.8

**Information**
 - Day.js Version [e.g. v1.0.0] 1.10.1
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome 62] Chrome 87
 - Time zone: [e.g. GMT-07:00 DST (Pacific Daylight Time)] GMT+8

**Comment by Mister-Hope** [comment]
I think it is related to https://github.com/iamkun/dayjs/issues/1281#issuecomment-754381268

For me I have to use `import dayjs from 'dayjs'` instead of `import * as dayjs from 'dayjs'`
